# Site settings
name: Rod Xavier Bondoc
title: Rod Xavier
email: hello@rodxavier.com
twitter_username: rodxavier07
github_username: rodxavier
skype_id: rod.xavier.bondoc
stackoverflow_id: 1134851/rod-xavier
linkedin: rodxavierbondoc
domain: rodxavier.com
description: ""
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalinks: pretty
