# Site settings
name: Rod Xavier Bondoc
title: Rod Xavier
email: rodxavier14@gmail.com
twitter_username: rodxavier14
github_username: rodxavier
skype_id: rod.xavier.bondoc
stackoverflow_id: 1134851
linkedin: rodxavierbondoc
domain: rodxavier.com
description: ""
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalinks: pretty
