remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"
url: "https://rodxavier.com"

read_time: true
words_per_minute: 200

mathjax: true

layout: home
paginate: true
paginate: 10
paginate_path: /page:num/

search_full_content: true

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Site Author
author:
  name: "Rod Xavier Bondoc"
  picture:
  email: "rod.xavier.bondoc@gmail.com"
  twitter: "@rodxavier07"
  links:
    - title:
      url:
      icon:

