remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"
url: "https://rodxavier.com"
date_format: "%Y-%m-%d"

read_time: true
words_per_minute: 200

mathjax: true

paginate: 10
paginate_path: /page:num/

search_full_content: true

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Site settings
locale: "en-au"
title: "{ Code Xavier }"
description: "A personal blog of a dad programmer"

# Site Author
author:
  name: "Rod Xavier Bondoc"
  picture: /images/rod.jpg
  email: "rod.xavier.bondoc@gmail.com"
  twitter: "rodxavier07"

footer_links:
  - title: Twitter
    url: https://twitter.com/rodxavier07
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/rodxavier
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

markdown: kramdown
feed:
  path: atom.xml
